spring:
  profiles:
    active: ${active:dev}
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_DATABASE:data_base_here}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: always
      schema-locations: classpath*:/sql/*.sql
  task:
    execution:
      pool:
        core-size: 10
        max-size: 100
        keep-alive: 60s
        queue-capacity: 1000
      thread-name-prefix: executor-
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: ${JOB_INIT_SCHEMA:never}
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
server:
  cookie-name: ${COOKIE_NAME:token}
  remember-me-hash-key: ${COOKIE_HASH:cs.jou}
  always-remember-me: ${REMEMBER_ME:false}
  port: ${SERVER_PORT:8080}
doc-info:
  title: web app API文档
  description:
  version: v1.0.1
  website-name: API文档
  website-url:
